name: task-a

on:
    pull_request:
        branches:
            - main
        # Paths to watch that will trigger the workflow
        paths:
            - "task_a/**"

jobs:
    test:
        runs-on: ${{ matrix.os }}
        name: pytest
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ["3.10", "3.11", "pypy3.10"]
                exclude:
                    - os: macos-latest
                      python-version: "3.10"
                    - os: windows-latest
                      python-version: "3.10"
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  cache: "pip"
            - name: Setup virtual environment
              run: |
                  python -m venv venv
                  source venv/bin/activate
              if: runner.os != 'Windows'
            - name: Setup virtual environment
              run: |
                  python -m venv venv
                  venv\Scripts\activate
              if: runner.os == 'Windows'
            - name: Install dependencies
              run: |
                  pip install -r ./task_a/requirements.txt
            - name: Run tests
              run: |
                  pytest ./task_a/task_a.py --html=report.html --self-contained-html
            - name: Upload test results
              uses: actions/upload-artifact@v2
              with:
                  name: test-results
                  path: ./report.html
