name: task-a

on: [push]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        name: pytest
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ["3.10", "3.11", "pypy3.10"]
                exclude:
                    - os: macos-latest
                      python-version: "3.10"
                    - os: windows-latest
                      python-version: "3.10"
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  cache: "pip"
            - name: Setup virtual environment
              run: |
                  python -m venv venv
                  if [ -f "venv/bin/activate" ]; then
                    source venv/bin/activate  # For Linux
                  elif [ -f "venv/Scripts/activate" ]; then
                    . venv/Scripts/activate  # For Windows
                  else
                    echo "Error: Failed to activate virtual environment."
                    exit 1
                  fi
            - name: Install dependencies
              run: |
                  pip install -r ./task_a/requirements.txt
            - name: Run tests
              run: |
                  pytest ./task_a/task_a.py --html=report.html --self-contained-html
            - name: Upload test results
              uses: actions/upload-artifact@v2
              with:
                  name: test-results
                  path: ./report.html
